---
# XXX: Refactor to work for X users
- name: Create database user 'aslcert01'
  mysql_user:
    name: "{{ mysql_aslcert01_username }}"
    password: "{{ mysql_aslcert01_password }}"
    priv: >-
      imovies.users:SELECT (uid, lastname, firstname, email, pwd),UPDATE (pwd)/
      imovies_ca.public_certificates:SELECT,INSERT,UPDATE (serial_number, uid, public_cert, revoked)/
      imovies_ca.private_certificates:SELECT,INSERT,UPDATE (sk_id, uid, private_cert)
    host: aslcert01
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslcert02'
  mysql_user:
    name: "{{ mysql_aslcert02_username }}"
    password: "{{ mysql_aslcert02_password }}"
    priv: >-
      imovies.users:SELECT (uid, lastname, firstname, email, pwd),UPDATE (pwd)/
      imovies_ca.public_certificates:SELECT,INSERT,UPDATE (serial_number, uid, public_cert, revoked)/
      imovies_ca.private_certificates:SELECT,INSERT,UPDATE (sk_id, uid, private_cert)
    host: aslcert02
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslweb01'
  mysql_user:
    name: "{{ mysql_aslweb01_username }}"
    password: "{{ mysql_aslweb01_password }}"
    priv: >-
      imovies.users:SELECT (uid, lastname, firstname, email, pwd),UPDATE (lastname, firstname, email)/
      imovies_ca.public_certificates:SELECT (serial_number, uid, public_cert, revoked)/
      imovies.admins:SELECT
    host: aslweb01
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslweb02'
  mysql_user:
    name: "{{ mysql_aslweb02_username }}"
    password: "{{ mysql_aslweb02_password }}"
    priv: >-
      imovies.users:SELECT (uid, lastname, firstname, email, pwd),UPDATE (lastname, firstname, email)/
      imovies_ca.public_certificates:SELECT (serial_number, uid, public_cert, revoked)/
      imovies.admins:SELECT
    host: aslweb02
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'backup'
  mysql_user:
    name: "{{ mysql_backup_username }}"
    password: "{{ mysql_backup_password }}"
    priv: "*.*:SELECT,LOCK TABLES,SHOW VIEW,EVENT,TRIGGER"
    host: localhost
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Modify nonlocal users to require TLS connections.
  mysql_user:
    name: "{{ item }}"
    append_privs: yes
    priv: '*.*:REQUIRESSL'
    state: present
  with_items:
    - aslcert01
    - aslcert02
    - aslweb01
    - aslweb02
