---
- name: Create database user 'aslcert01'
  mysql_user:
    name: "{{ mysql_aslcert01_username }}"
    password: "{{ mysql_aslcert01_password }}"
    priv: >-
      imovies.users:SELECT
      (uid, lastname, firstname, email, pwd)/imovies.users:UPDATE
      (pwd)/imovies_ca.public_certificates:SELECT
      (serial_number, uid, public_cert, revoked)/imovies_ca.public_certificates:INSERT
      (serial_number, uid, public_cert, revoked)/imovies_ca.public_certificates:UPDATE
      (serial_number, uid, public_cert, revoked)/imovies_ca.private_certificates:SELECT
      (sk_id, uid, private_cert)/imovies_ca.private_certificates:UPDATE
      (sk_id, uid, private_cert)/imovies_ca.private_certificates:INSERT
      (sk_id, uid, private_cert)
    host: aslcert01
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslcert02'
  mysql_user:
    name: "{{ mysql_aslcert02_username }}"
    password: "{{ mysql_aslcert02_password }}"
    priv: >-
      imovies.users:SELECT
      (uid, lastname, firstname, email, pwd)/imovies.users:UPDATE
      (pwd)/imovies_ca.public_certificates:SELECT
      (serial_number, uid, public_cert, revoked)/imovies_ca.public_certificates:INSERT
      (serial_number, uid, public_cert, revoked)/imovies_ca.public_certificates:UPDATE
      (serial_number, uid, public_cert, revoked)/imovies_ca.private_certificates:SELECT
      (sk_id, uid, private_cert)/imovies_ca.private_certificates:UPDATE
      (sk_id, uid, private_cert)/imovies_ca.private_certificates:INSERT
      (sk_id, uid, private_cert)
    host: aslcert02
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslweb01'
  mysql_user:
    name: "{{ mysql_aslweb01_username }}"
    password: "{{ mysql_aslweb01_password }}"
    priv: >-
      imovies.users:SELECT
      (uid, lastname, firstname, email, pwd)/imovies.users:UPDATE
      (lastname, firstname, email)/imovies_ca.public_certificates:SELECT
      (serial_number, uid, public_cert, revoked)
    host: aslweb01
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Create database user 'aslweb02'
  mysql_user:
    name: "{{ mysql_aslweb02_username }}"
    password: "{{ mysql_aslweb02_password }}"
    priv: >-
      imovies.users:SELECT
      (uid, lastname, firstname, email, pwd)/imovies.users:UPDATE
      (lastname, firstname, email)/imovies_ca.public_certificates:SELECT
      (serial_number, uid, public_cert, revoked)
    host: aslweb02
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
