---
- name: Create a legacy database 'imovies'
  mysql_db:
    name: imovies
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Copy database dump file
  copy:
    src: imovies_users.dump
    dest: /tmp

- name: Restore legacy db imovies
  mysql_db:
    name: imovies
    state: import
    target: /tmp/imovies_users.dump
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: Copy CA admins table script
  copy:
    src: imovies_users_admins_table.sql
    dest: /tmp

- name: Create the CA admins table
  mysql_db:
    name: imovies
    state: import
    target: /tmp/imovies_users_admins_table.sql
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

# XXX: maybe shred first
- name: Remove dump
  file:
    path: /tmp/imovies_users.dump
    state: absent

- name: Remove CA admins table script
  file:
    path: /tmp/imovies_users_admins_table.sql
    state: absent
