---
- name: Create a legacy database 'imovies'
  mysql_db:
    name: imovies
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"

- name: Copy database dump file
  copy:
    src: imovies_users.dump
    dest: /tmp

- name: Restore legacy db imovies
  mysql_db:
    name: imovies
    state: import
    target: /tmp/imovies_users.dump
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"

# XXX: maybe shred first
- name: Remove dump
  file:
    path: /tmp/imovies_users.dump
    state: absent
