---
- name: Install GnuPG to import keys.
  package:
    name: gpg
    state: present
    update_cache: true

- name: Import MariaDB APT key
  apt_key:
    url: "{{ mariadb_apt_repo_gpg_key_url }}"
    state: present

- name: Add repository for Debian Buster
  apt_repository:
    repo: deb [arch=amd64] http://mirror.mva-n.net/mariadb/repo/10.4/debian buster main
    state: present
    update_cache: yes

- name: Install MariaDB
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "mariadb-server"
    - "mariadb-client"
    - "python-mysqldb"
    - "rsync"
