---
- name: Create include directory for nginx
  file:
    path: "/etc/nginx/include.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install systemd unit file
  template:
    src: ssl_client.conf.j2
    dest: /etc/nginx/include.d/ssl_client.conf
    owner: root
    group: root
    mode: 0644
