---
- name: Install the package
  package:
    name: nftables
    state: present
    update_cache: true

- name: Enable the service
  systemd:
    name: nftables.service
    enabled: yes
    masked: no

- name: Start the service
  command: systemctl restart nftables.service
  async: 5
  poll: 0
