---
- name: Generate RSA keys for root CA
  openssl_privatekey:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"
    type: RSA
    size: 4096
    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"

- name: Create CSR for root CA
  openssl_csr:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.csr"
    privatekey_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"

    country_name: "{{ COUNTRY_NAME }}"
    state_or_province_name: "{{ STATE_OR_PROVINCE_NAME }}"
    locality_name: "{{ LOCALITY_NAME }}"
    organization_name: "{{ ORGANIZATION_NAME }}"
    common_name: "{{ CORE_CA_CN }}"
    # Add when upgraded to ansible 2.8
    # use_common_name_for_san: false

    basic_constraints: "CA:true"
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature

    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"

- name: Create Certificate for root CA
  openssl_certificate:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
    privatekey_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"
    csr_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.csr"
    provider: selfsigned
    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"
