---
- name: Generate RSA keys for core CA
  openssl_privatekey:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"
    type: RSA
    size: 4096
    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"

- name: Create CSR
  openssl_csr:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.csr"
    privatekey_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"

    country_name: CH
    state_or_province_name: Zurich
    locality_name: Zurich
    organization_name: iMovies
    common_name: "iMovies Core CA"

    basic_constraints: "CA:true"
    key_usage:
      - keyCertSign
      - cRLSign
      - digitalSignature

    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"

- name: Create Certificate
  openssl_certificate:
    path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
    privatekey_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"
    csr_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.csr"
    provider: selfsigned
    force: "{{ FORCE_ROOT_CA_CERT_REGEN }}"
