---
- name: Set default values
  set_fact:
    revoke_all: "{{ revoke_all | default(false) }}"

# Loop over all certificates in {{ ca_folder }}/certs and revoke them
- name: Gather certificates to revoke
  find:
    paths: "{{ ca_folder }}/certs"
    patterns: "*.crt"
  register: crt_files_glob
  when: revoke_all

- name: Store certificates to revoke
  set_fact:
    certs_to_revoke: "{{ (crt_files_glob.files | map(attribute='path') | list) if revoke_all else cert_to_revoke }}"

- name: "Revoke all certificates in {{ ca_folder }}/certs"
  command: |
    openssl ca -config {{ ca_folder }}/{{ openssl_conf_name }} \
    -revoke {{ item }}
  with_items:
    - "{{ certs_to_revoke }}"

- name: "Move revoked certificates"
  command: mv {{ item }} {{ ca_folder }}/revokedcerts/
  with_items:
    - "{{ certs_to_revoke }}"

- name: Generate new CRL
  command: |
    openssl ca -config {{ openssl_conf_name }} \
    -gencrl -out {{ crl_name }}
  args:
    chdir: "{{ ca_folder }}/"
