---
- name: Fetch a pre-generated DH parameters file
  synchronize:
    src: "/vagrant/dhparams_store/{{ ansible_hostname }}.pem"
    dest: /etc/ssl/private/dh_param.pem
    group: false
    owner: false

- name: Set permissions for DH parameters file
  file:
    path: /etc/ssl/private/dh_param.pem
    owner: root
    group: root
    mode: 0440
