---
- name: Init Backup repo
  command: >-
    borg init --encryption=keyfile-blake2
    {{ hostvars[groups['bkpservers'][0]]['UNAME'] }}@{{ item }}:{{ BACKUP_PATH_ROOT }}/{{ inventory_hostname }}
    --rsh 'sudo -u {{ backup_client_username }}
    ssh -oStrictHostKeyChecking=accept-new -i /home/{{ backup_client_username }}/.ssh/id_rsa_backup'
  loop: "{{ groups['bkpservers'] }}"
