---
- name: Include phasephrase variables
  include_vars:
    file: /vagrant/borg_phasephrases.yml
- import_tasks: service.yml
- import_tasks: init_backup_repos.yml
  tags: [never, setup]
- import_tasks: ca_allow_bkup.yml
