---
- name: Install systemd unit file
  template:
    src: asl-webserver.service.j2
    dest: /etc/systemd/system/asl-webserver.service
    owner: "{{ UNAME }}"
    group: "{{ UNAME }}"
    mode: 0644

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable the service
  systemd:
    name: asl-webserver
    enabled: yes
    masked: no

- name: Start the service
  systemd:
    name: asl-webserver
    state: restarted
