---
- name: Creates directory
  file:
    path: "/home/{{ UNAME }}/app"
    state: directory
    owner: "{{ UNAME }}"
    group: "{{ UNAME }}"
    mode: 0770

- name: Download the latest release of WebServer
  get_url:
    url: https://github.com/Liblor/applied_security_lab_deploy/releases/latest/download/WebServer.tar.gz
    dest: "/home/{{ UNAME }}/app/WebServer.tar.gz"
    mode: 0640

- name: Unpack the downloaded archive
  unarchive:
    src: "/home/{{ UNAME }}/app/WebServer.tar.gz"
    dest: "/home/{{ UNAME }}/app"
    remote_src: yes

- name: Remove the archive
  file:
    state: absent
    path: "/home/{{ UNAME }}/app/WebServer.tar.gz"
