---
- name: mount /proc
  become: 'yes'
  become_method: sudo
  mount:
    name: /proc
    src: none
    fstype: proc
    opts: rw,nosuid,nodev,noexec,relatime,hidepid=2
    state: present
  tags:
    - mount
    - proc
    - security
...
