---
- name: access.conf
  become: 'yes'
  become_method: sudo
  template:
    src: etc/security/access.conf.j2
    dest: /etc/security/access.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - access.conf
    - security

- name: securetty
  become: 'yes'
  become_method: sudo
  template:
    src: etc/securetty.j2
    dest: /etc/securetty
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - securetty
    - security

- name: mask debug-shell
  become: 'yes'
  become_method: sudo
  systemd:
    name: debug-shell.service
    masked: 'yes'
    enabled: 'no'
    state: stopped
  tags:
    - systemd
    - debug-shell
    - security
...
