---
- name: remove suid/sgid
  become: 'yes'
  become_method: sudo
  file:
    path: "{{ item }}"
    mode: 'a-s'
    state: file
    follow: 'yes'
  ignore_errors: true
  with_items:
    - "{{ suid_sgid_blacklist }}"
  tags:
    - suid
    - security
...
