---
- name: remove users
  become: 'yes'
  become_method: sudo
  user:
    name: "{{ item }}"
    state: absent
    remove: 'yes'
  with_items:
    - gnats
    - irc
    - list
    - news
    - uucp
  ignore_errors: true
  tags:
    - users
    - security
...
