---
- hosts: ansservers
  become: yes
  roles:
    - pyopenssl
    - asl-ansserver-init
    - prepare-openssl-ca
  vars:
    ca_folder: "/home/{{ UNAME }}/root_ca"
    openssl_conf_name: Root-CA-openssl.cnf
    ca_cert_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_crt.pem"
    ca_priv_key_path: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_key.pem"
    crl_file_name: Root_CA_crl.pem
  tasks:
    - name: Store CA certificate on ansible host
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_crt.pem"
        dest: /usr/local/share/ca-certificates

    - name: Chown core CA certificate
      file:
        path: /usr/local/share/ca-certificates/iMovies_Root_CA.crt
        owner: root
        group: root

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Distribute root CA certificate
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA_crt.pem"
        dest: /usr/local/share/ca-certificates
      when: FORCE_ROOT_CA_CERT_REGEN

    - name: Chown root CA certificate
      file:
        path: /usr/local/share/ca-certificates/iMovies_Root_CA_crt.pem
        owner: root
        group: root
      when: FORCE_ROOT_CA_CERT_REGEN

    - name: Update certificate store
      command: update-ca-certificates
      when: FORCE_ROOT_CA_CERT_REGEN

- import_playbook: issue-intermediate-certs.yml
- import_playbook: issue-tls-certs.yml
