---
- hosts: ansservers
  connection: local
  become: yes
  roles:
    - add-user
    - pyopenssl
    - asl-ansserver-init
  tasks:
    - name: Store CA certificate on ansible host
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
        dest: /usr/share/ca-certificates/mozilla/

    - name: Chown core CA certificate
      file:
        path: /usr/share/ca-certificates/mozilla/iMovies_Root_CA.crt
        owner: root
        group: root

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Distribute root CA certificate
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
        dest: /usr/share/ca-certificates/mozilla/

    - name: Chown root CA certificate
      file:
        path: /usr/share/ca-certificates/mozilla/iMovies_Root_CA.crt
        owner: root
        group: root

    - name: Create symlink to root CA certificate
      file:
        src: /usr/share/ca-certificates/mozilla/iMovies_Root_CA.crt
        dest: /etc/ssl/certs/iMovies_Root_CA.crt
        owner: root
        group: root
        state: link

- import_playbook: issue-intermediate-certs.yml
- import_playbook: issue-tls-certs.yml
