---
- hosts: certservers
  become: yes
  tasks:
    - name: Create backup directory
      file:
        path: "/home/{{ UNAME }}/backup"
        state: directory
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: 0700
  roles:
    - borgbackup
    - backup-client
  vars:
    backup_files:
      - "/home/{{ UNAME }}/backup"

- hosts: certservers
  become: yes
  roles:
    - asl-certserver
    - nginx-ssl-client
    - nginxinc.nginx
    - add-to-trusted-user-group
  vars:
    trusted_user: nginx
    ssl_client_required: true
  vars_files:
    - nginx_vars.yml
