---
- hosts: dbservers
  become: yes
  vars_files:
    - /vagrant/mysql_passwords.yml
  roles:
    - mariadb
    - asl-dbserver
  tags: [ never, setup ]

- hosts: asldb01
  become: yes
  vars_files:
    - /vagrant/mysql_passwords.yml
  roles:
    - init_db
  tags: [ never, setup ]
