---
# === Galera Cert setup === #

# create server csr
- hosts: dbservers
  become: yes
  tasks:
    - name: Create Galera Rep keys
      openssl_privatekey:
        path: "{{ GALERA_KEY }}"
        type: RSA
        size: 4096
        force: yes
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: 0640

    # use openssl commmand because
    # ansibles openssl adds extention that is not
    # compatible with galera...
    # andible 2.8 supports 'useCommonNameForSAN: no'
    # but we use older version
    - name: Create CSR for Galera Rep
      shell: >-
        openssl req -new -nodes
        -days 365000
        -key {{ GALERA_KEY }}
        -out /etc/mysql/keys/{{ inventory_hostname }}_galera.csr
        -subj
        "/C={{ COUNTRY_NAME }}/ST={{ STATE_OR_PROVINCE_NAME }}/O={{ ORGANIZATION_NAME }}/CN={{ ansible_eth1.ipv4.address }}"

    - name: Fetch CSR
      fetch:
        flat: yes
        src: "/etc/mysql/keys/{{ inventory_hostname }}_galera.csr"
        dest: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/{{ inventory_hostname }}_galera.csr"
  vars:
    - GALERA_KEY: "/etc/mysql/keys/{{ inventory_hostname }}_galera_key.pem"
  tags: galera_tls

# create self-signed ca and sign csr
- hosts: aslans01
  become: yes
  tasks:
    - name: Generate RSA keys for Galera replication traffic CA
      openssl_privatekey:
        path: "{{ DB_CA_KEY }}"
        type: RSA
        size: 4096
        owner: "root"
        group: "root"
        force: yes

    - name: "Create CSR for CA"
      shell: >-
        openssl req -new -x509 -nodes
        -days 365000 
        -key {{ DB_CA_KEY }}
        -out {{ DB_CA_CRT }}
        -subj
        "/C={{ COUNTRY_NAME }}/ST={{ STATE_OR_PROVINCE_NAME }}/O={{ ORGANIZATION_NAME }}/CN=iMovies Galera CA"

    - name: Sign DB Certs
      openssl_certificate:
        path: "/home/{{ UNAME }}/{{ item }}_galera.crt"
        csr_path: "/home/{{ UNAME }}/{{ item }}_galera.csr"
        ownca_path: "{{ DB_CA_CRT }}"
        ownca_privatekey_path: "{{ DB_CA_KEY }}"
        provider: ownca
      loop: "{{ groups['dbservers'] }}"
  vars:
    - DB_CA_KEY: "/home/{{ UNAME }}/ca-key.pem"
    - DB_CA_CSR: "/home/{{ UNAME }}/ca-cert.csr"
    - DB_CA_CRT: "/home/{{ UNAME }}/ca-cert.pem"
  tags: galera_tls

- hosts: dbservers
  become: yes
  tasks:
    - name: "Include galera CA cert"
      copy:
        src: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/ca-cert.pem"
        dest: "/etc/mysql/keys/ca-cert.pem"
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: '0644'

    - name: "Include galera db cert"
      copy:
        src: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/{{ inventory_hostname }}_galera.crt"
        dest: "/etc/mysql/keys/{{ inventory_hostname }}_galera_cert.pem"
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: '0644'
  tags: galera_tls


# === DB setup === #

- hosts: dbservers
  become: yes
  vars_files:
    - /vagrant/mysql_passwords.yml
  roles:
    - add-to-trusted-user-group
    - mariadb
    - asl-dbserver
  vars:
    trusted_user: mysql
  tags: setup

- hosts: asldb01
  become: yes
  vars_files:
    - /vagrant/mysql_passwords.yml
  roles:
    - init_db
  tags: [ never, setup ]
