---
- hosts: ansservers
  become: yes
  tasks:
    - name: Store CA certificate on ansible host
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
        dest: /usr/local/share/ca-certificates

    - name: Chown core CA certificate
      file:
        path: /usr/local/share/ca-certificates/iMovies_Root_CA.crt
        owner: root
        group: root

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Distribute root CA certificate
      synchronize:
        src: "/{{ VAGRANT_SHARED_FOLDERNAME }}/key_store/iMovies_Root_CA.crt"
        dest: /usr/local/share/ca-certificates
      when: FORCE_ROOT_CA_CERT_REGEN

    - name: Chown root CA certificate
      file:
        path: /usr/local/share/ca-certificates/iMovies_Root_CA.crt
        owner: root
        group: root
      when: FORCE_ROOT_CA_CERT_REGEN

    - name: Update certificate store
      command: update-ca-certificates
      when: FORCE_ROOT_CA_CERT_REGEN
