---
- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Add group for SSH
      group:
        name: sshuser
        state: present
    - name: Add ansible user to SSH group
      user:
        name: ansible
        groups: sshuser
        append: yes
    - name: Add vagrant user to SSH group
      user:
        name: vagrant
        groups: sshuser
        append: yes

- hosts: all, !ansservers
  become: yes
  roles:
    - hardening
  vars:
    ssh_allow_groups: sshuser

- hosts: ansservers
  become: yes
  roles:
    - hardening
  vars:
    ssh_allow_groups: sshuser

- hosts: all
  become: yes
  roles:
    - lynis
