---
- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Add group for SSH
      group:
        name: sshuser
        state: present
    - name: Add ansible user to SSH group
      user:
        name: ansible
        groups: sshuser
        append: yes
    # TODO Remove this task for final submission.
    - name: Add vagrant user to SSH group
      user:
        name: vagrant
        groups: sshuser
        append: yes

- hosts: all, !ansservers
  become: yes
  roles:
    - hardening
  vars:
    # TODO Adjust this once Vagrant no longer needs access.
    sshd_admin_net: [127.0.0.1/8,172.16.0.11/16,10.0.0.0/16]
    ssh_allow_groups: sshuser

- hosts: ansservers
  become: yes
  roles:
    - hardening
  vars:
    # TODO Adjust this once Vagrant no longer needs access.
    # TODO Once a firewall is installed, adjust this to the public network.
    sshd_admin_net: [127.0.0.1/8,172.16.0.11/16,10.0.0.0/16]
    ssh_allow_groups: sshuser

- hosts: all
  become: yes
  roles:
    - lynis
