---
- hosts: all
  become: yes
  tasks:
    - name: Add group for SSH
      group:
        name: sshuser
        state: present

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Add ansible user to SSH group
      user:
        name: ansible
        groups: sshuser
        append: yes

- hosts: ansservers
  become: yes
  tasks:
    - name: Add admin user to SSH group
      user:
        name: admin
        groups: sshuser
        append: yes

- hosts: all
  become: yes
  roles:
    - hardening
    - lynis
  vars:
    ssh_allow_groups: sshuser
