---
# The first cert server signs the admin CA cert for the reviewing group
- hosts: "{{ groups['certservers'][0] }}"
  become: yes
  tasks:
    - name: Move admin certificate issuing script to config server
      synchronize:
        src: /vagrant/scripts/issue_ca_admin_cert.py
        dest: /tmp/

    - name: Obtain CA admin certificate
      command: "python3 /tmp/issue_ca_admin_cert.py /home/{{ UNAME }}/ca_admin_cert_with_priv_key.pfx"

    - name: Pull CA admin certificate to config server
      synchronize:
        mode: pull
        src: "/home/{{ UNAME }}/ca_admin_cert_with_priv_key.pfx"
        dest: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/ca_admin_cert_with_priv_key.pfx"
        group: false
        owner: false
      delegate_to: "{{ groups['ansservers'][0] }}"

    - name: Remove CA admin certificate from cert server
      file:
        state: absent
        path: "/home/{{ UNAME }}/ca_admin_cert_with_priv_key.pfx"

    - name: Remove admin certificate issuing script from certificate server
      file:
        name: /tmp/issue_ca_admin_cert.py
        state: absent
