---
- hosts: ansservers
  tasks:
    - name: Create folder for TLS CSR and certificates
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
      with_items:
        - "/home/{{ UNAME }}/tls/csr"
        - "/home/{{ UNAME }}/tls/crl"
        - "/home/{{ UNAME }}/tls/certs"

- hosts: all, !ansservers
  become: yes
  roles:
    - pyopenssl
  tasks:
    - name: Create HTTPS keys
      openssl_privatekey:
        path: "/etc/ssl/trusted/private/iMovies_{{ ansible_hostname }}_tls_key.pem"
        type: RSA
        size: 4096
        force: "{{ FORCE_TLS_CERT_REGEN }}"

        owner: root
        group: "{{ TLS_GROUP }}"
        mode: 0640

    - name: Create CSR for HTTPS keys
      openssl_csr:
        path: "/etc/ssl/trusted/csr/iMovies_{{ ansible_hostname }}_tls.csr"
        privatekey_path: "/etc/ssl/trusted/private/iMovies_{{ ansible_hostname }}_tls_key.pem"

        country_name: "{{ COUNTRY_NAME }}"
        state_or_province_name: "{{ STATE_OR_PROVINCE_NAME }}"
        locality_name: "{{ LOCALITY_NAME }}"
        organization_name: "{{ ORGANIZATION_NAME }}"
        common_name: "{{ ansible_hostname }}"
        # Externally reachable servers have the imovies domain as SAN
        subjectAltName: "{{ 'DNS:www.imovies.ch, ' + 'DNS:' + ansible_hostname if ('webservers' in groups and ansible_hostname in groups['webservers']) else 'DNS:' + ansible_hostname }}"

        key_usage:
          - digitalSignature
          - keyEncipherment

        extendedKeyUsage:
          - serverAuth
          - clientAuth

        force: "{{ FORCE_TLS_CERT_REGEN }}"

        owner: root
        group: "{{ TLS_GROUP }}"

    - name: Transfer CSR to config server
      synchronize:
        mode: pull
        src: "/etc/ssl/trusted/csr/iMovies_{{ ansible_hostname }}_tls.csr"
        dest: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/tls/csr/"
        group: false
        owner: false
      delegate_to: "{{ groups['ansservers'][0] }}"

- hosts: certservers
  become: yes
  roles:
    - role: revoke-all-certs
      when: FORCE_TLS_CERT_REGEN
  vars:
    ca_folder: "/home/{{ UNAME }}/intermediate_ca"
    openssl_conf_name: Intermediate-CA-openssl.cnf
    crl_name: Intermediate_CA.crl
  tasks:
    - name: Transfer CRL to config server
      synchronize:
        mode: pull
        src: "/home/{{ UNAME }}/intermediate_ca/Intermediate_CA.crl"
        dest: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/tls/crl"
        group: false
        owner: false
      delegate_to: "{{ groups['ansservers'][0] }}"

- hosts: ansservers
  become: yes
  tasks:
    - name: Move TLS CRL to privileged folder
      synchronize:
        src: tls/crl/
        dest: /etc/pki/tls/crl/

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Distribute new CRL
      synchronize:
        src: /etc/pki/tls/crl/
        dest: /etc/pki/tls/crl/
        rsync_path: "sudo rsync"

    - name: Combine Root CA and intermediate CA CRL
      shell: |
        cat /etc/pki/tls/crl/Root_CA.crl /etc/pki/tls/crl/Intermediate_CA.crl \
        > /etc/pki/tls/crl/tls_crl_chain.pem

# The first core ca signs all internal tls certificates
- hosts: "{{ groups['certservers'][0] }}"
  become: yes
  tasks:
    - name: Create folder for CSRs for TLS certificates on certserver
      file:
        path: "/home/{{ UNAME }}/intermediate_ca/csr/tls"
        state: directory
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"

    - name: Transfer CSR to cert server
      synchronize:
        src: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/tls/csr/"
        dest: "/home/{{ UNAME }}/intermediate_ca/csr/tls/"
        group: false
        owner: false

    # Loop over all files in tls/csr and sign their certificate, the name of which
    # is for <name>.csr --> <name>.crt
    - name: Gather CSRs to sign
      find:
        paths: "/home/{{ UNAME }}/intermediate_ca/csr/tls"
        patterns: "*.csr"
      register: csr_files_glob

    - name: Sign remote server CSRs to create TLS certificates
      command: |
        openssl ca -batch -config Intermediate-CA-openssl.cnf \
        -extensions server_cert -notext \
        -in {{ item.path }} \
        -out certs/{{ item.path | basename | splitext | first }}.crt
      args:
        chdir: "/home/{{ UNAME }}/intermediate_ca/"
      with_items:
        - "{{ csr_files_glob.files }}"
      when: FORCE_TLS_CERT_REGEN

    - name: Fix certificate permissions
      file:
        path: "/home/{{ UNAME }}/intermediate_ca/certs/{{ item.path | basename | splitext | first }}.crt"
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
      with_items:
        - "{{ csr_files_glob.files }}"
      when: FORCE_TLS_CERT_REGEN

    - name: Create folders for TLS chains
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: 0700
      with_items:
        - "/home/{{ UNAME }}/intermediate_ca/chains"

    - name: Create certificate chain
      shell: |
        cat "/home/{{ UNAME }}/intermediate_ca/certs/{{ item.path | basename | splitext | first }}.crt" \
        "/home/{{ UNAME }}/pki/certs/iMovies_{{ INTERMEDIATE_CERT_PURPOSES[0] }}_{{ ansible_hostname }}_Intermediate_CA.crt" \
        > "/home/{{ UNAME }}/intermediate_ca/chains/{{ item.path | basename | splitext | first }}.crt"
      when: FORCE_TLS_CERT_REGEN
      with_items:
        - "{{ csr_files_glob.files }}"

    - name: Transfer certs to config server
      synchronize:
        mode: pull
        src: "/home/{{ UNAME }}/intermediate_ca/chains/"
        dest: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/tls/certs/"
        group: false
        owner: false
      when: FORCE_TLS_CERT_REGEN
      delegate_to: "{{ groups['ansservers'][0] }}"

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Transfer certificates to corresponding hosts
      synchronize:
        src: "/home/{{ hostvars[groups['ansservers'][0]]['UNAME'] }}/tls/certs/iMovies_{{ ansible_hostname }}_tls.crt"
        dest: /etc/pki/tls/certs/
      when: FORCE_TLS_CERT_REGEN

    - name: Fix certificate permissions
      file:
        path: "/etc/pki/tls/certs/iMovies_{{ ansible_hostname }}_tls.crt"
        owner: root
        group: root
        mode: 0644
      when: FORCE_TLS_CERT_REGEN


- hosts: dbservers
  become: yes
  tasks:
    - name: Creates directory for mariaDB keys
      file:
        path: /etc/mysql/keys
        state: directory
        owner: mysql
        group: mysql
        mode: 0700

    - name: Convert private key to pkcs#1
      command: "openssl rsa -in /home/{{ UNAME }}/pki/private/iMovies_{{ansible_hostname}}_tls_key.pem -out /etc/mysql/keys/iMovies_{{ inventory_hostname }}_tls_key.pem"

    - name: Fix mysql private key permissions
      file:
        path: "/etc/mysql/keys/iMovies_{{ inventory_hostname }}_tls_key.pem"
        owner: "{{ UNAME }}"
        group: "{{ UNAME }}"
        mode: 0600
