---
- hosts: ansservers
  connection: local
  tasks:
    - name: Create folder for TLS CSR and certificates
      file:
        path: "{{ item }}"
        state: directory
        owner: ansible
        group: ansible
      with_items:
        - /home/ansible/tls_csr
        - /home/ansible/tls_certs

- hosts: all, !ansservers
  become: yes
  roles:
    - pyopenssl
  tasks:
    - name: Create folder for TLS keys
      file:
        path: /etc/pki/tls/private
        state: directory
        mode: 0750
        # XXX: Do we have a general user that runs those
        # services, so that we can only give that user access?

    - name: Create folder for TLS CSR
      file:
        path: /etc/pki/tls/csr
        state: directory
        mode: 0750
        # XXX: Do we have a general user that runs those
        # services, so that we can only give that user access?

    - name: Create folder for TLS CSR
      file:
        path: /etc/pki/tls/certs
        state: directory
        mode: 0750
        # XXX: Do we have a general user that runs those
        # services, so that we can only give that user access?

    - name: Create HTTPS keys
      openssl_privatekey:
        path: "/etc/pki/tls/private/{{ansible_hostname}}_tls_key.pem"
        type: RSA
        size: 4096

    - name: Create CSR for HTTPS keys
      openssl_csr:
        path: "/etc/pki/tls/csr/{{ansible_hostname}}_tls.csr"
        privatekey_path: "/etc/pki/tls/private/{{ansible_hostname}}_tls_key.pem"

        country_name: CH
        state_or_province_name: Zurich
        locality_name: Zurich
        organization_name: iMovies
        common_name: "iMovies {{ansible_hostname}}"
        # Externally reachable servers have the imovies domain as SAN
        subjectAltName: "{{ 'DNS:www.imovies.ch' if ansible_hostname in groups['webservers'] else omit }}"

        key_usage:
          - digitalSignature
          - keyEncipherment

        extendedKeyUsage:
          - serverAuth
          - clientAuth

        force: true

    - name: Transfer CSR to config server
      synchronize:
        mode: pull
        src: "/etc/pki/tls/csr/{{ansible_hostname}}_tls.csr"
        dest: /home/ansible/tls_csr/
      delegate_to: "{{ groups['ansservers'][0] }}"

# The first core ca signs all internal tls certificates
- hosts: "{{ groups['certservers'][0] }}"
  become: yes
  tasks:
    - name: Create folders for TLS CSR and certificates
      file:
        path: "{{ item }}"
        state: directory
        owner: coreca
        group: coreca
      with_items:
        - /home/coreca/tls_certs
        - /home/coreca/tls_csr

    - name: Transfer CSR to cert server
      synchronize:
        src: /home/ansible/tls_csr/
        dest: /home/coreca/tls_csr/

    # Loop over all files in tls_csr and sign their certificate, the name of which
    # is for <name>.csr --> <name>.crt
    - name: Gather CSR's to sign
      find:
        paths: /home/coreca/tls_csr
        patterns: "*.csr"
      register: csr_files_glob

    - name: Sign remote server CSR's
      openssl_certificate:
        path: "/home/coreca/tls_certs/{{ item.path | basename | splitext | first }}.crt"
        csr_path: "{{ item.path }}"
        provider: ownca
        ownca_path: /home/coreca/pki/certs/{{ansible_hostname}}_intermediate_ca.crt
        ownca_privatekey_path: /home/coreca/pki/private/{{ansible_hostname}}_intermediate_ca_key.pem
        # Hack since the "+730d" syntax of this template seems to be broken
        ownca_not_after: "{{ lookup('pipe','date +\"%Y%m%d%H%M%SZ\" -d \"+365 days\"') }}"
      with_items:
        - "{{ csr_files_glob.files }}"

    - name: Transfer certs to config server
      synchronize:
        mode: pull
        src: "/home/coreca/tls_certs/"
        dest: /home/ansible/tls_certs/
      delegate_to: "{{ groups['ansservers'][0] }}"

    - name: Remove folders for TLS CSR and certificates
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/coreca/tls_csr
        - /home/coreca/tls_certs

- hosts: all, !ansservers
  become: yes
  tasks:
    - name: Transfer certs to corresponding hosts
      synchronize:
        src: "/home/ansible/tls_certs/{{ ansible_hostname }}_tls.crt"
        dest: /etc/pki/tls/certs/

    # XXX: Do we have a general user that runs those
    # services, so that we can only give that user access?
    # - name: Fix certificate permisions
    #   file:
    #     path: "/etc/pki/tls/certs/{{ ansible_hostname }}_tls.crt"
    #     owner: XXX
    #     group: XXX

- hosts: ansservers
  connection: local
  become: yes
  tasks:
    - name: Remove folder for TLS CSR and certificates
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/ansible/tls_csr
        - /home/ansible/tls_certs
