---
- hosts: logservers
  become: yes
  roles:
    - rsyslog-conf
  vars:
    rsyslog_conf_receive: true

- hosts: all, !logservers
  become: yes
  roles:
    - rsyslog-conf
  vars:
    rsyslog_conf_send: true
