---
- hosts: webservers
  become: yes
  vars_files:
    - /vagrant/mysql_passwords.yml
  roles:
    - asl-webserver
    - nginxinc.nginx
    - nginx-ssl-client
    - add-to-trusted-user-group
  vars:
    trusted_user: nginx
    ssl_client_required: false
  vars_files:
    - nginx_vars.yml
