---
- hosts: webservers
  become: yes
  roles:
    - add-to-trusted-user-group
    - asl-webserver
  vars:
    trusted_user: "{{ UNAME }}"
  vars_files:
    - /vagrant/mysql_passwords.yml

- hosts: webservers
  become: yes
  roles:
    - nginxinc.nginx
    - nginx-ssl-client
    - add-to-trusted-user-group
  vars:
    trusted_user: nginx
    ssl_client_required: false
  vars_files:
    - nginx_vars.yml
