- name: Distribute intermediate CA certificates
  command: |
    rsync
    --rsync-path="sudo rsync"
    -e "ssh -i .ssh/id_rsa"
    -og --chown=coreca:coreca
    "./intermediate_certs/{{item}}_intermediate_ca_cert.pem"
    "ansible@{{item}}:/home/coreca/keys/"
  with_inventory_hostnames:
    - certservers

- name: Distribute intermediate CA private keys
  command: |
    rsync
    --rsync-path="sudo rsync"
    -e "ssh -i .ssh/id_rsa"
    -og --chown=coreca:coreca
    "./intermediate_certs/{{item}}_intermediate_ca_cert_and_priv_key.pfx"
    "ansible@{{item}}:/home/coreca/keys/"
  with_inventory_hostnames:
    - certservers

- name: Remove intermediate CA certificates and keys from config server
  file:
    path: ./intermediate_certs
    state: absent
