---
#
# This user is used to push the backups to the backup server
#
- name: Add backup_client user
  user:
    name: "{{ backup_client_username }}"
    password_lock: yes
    shell: /sbin/nologin
    generate_ssh_key: yes
    ssh_key_type: "rsa"
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/id_rsa_backup"
    create_home: yes
    append: yes

- name: Fetch public key
  fetch:
    flat: yes
    src: "/home/{{ backup_client_username }}/.ssh/id_rsa_backup.pub"
    dest: "{{ BACKUP_SSH_PUBK_LOCAL_PATH_PREFIX + inventory_hostname }}.pub"

- name: Create a backup folder
  file:
    path: "/home/{{ UNAME }}/backup"
    state: directory
    owner: "{{ UNAME }}"
    group: "{{ UNAME }}"
    mode: 0700
  when: inventory_hostname in groups['dbservers'] or inventory_hostname in groups['certservers']
