---
- name: Create 60-server.cnf config
  template:
    src: 60-server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-server.cnf
    owner: root
    group: root
    mode: '0644'

- name: Stop service mariaDB, if running
  systemd:
    name: mysql
    state: stopped

- name: Restart mariaDB
  systemd:
    state: restarted
    daemon_reload: yes
    name: mariadb
