---
- name: Import Microsoft APT key
  apt_key:
    url: "{{ aspdotnet_apt_repo_gpg_key_url }}"
    state: present

- name: Add repository for Debian Buster
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main
    filename: "microsoft-prod"
    state: present
    update_cache: yes

- name: Install the package
  package:
    name: "{{ aspdotnet_package }}"
    state: present
    update_cache: true
