- name: Distribute immediate CA certificates
  command: |
    rsync
    --rsync-path="sudo rsync"
    -e "ssh -i .ssh/id_rsa"
    -og --chown=coreca:coreca
    "./immediate_certs/{{item}}_immediate_ca_cert.pem"
    "ansible@{{item}}:/home/coreca/keys/"
  with_inventory_hostnames:
    - certservers

- name: Distribute immediate CA private keys
  command: |
    rsync
    --rsync-path="sudo rsync"
    -e "ssh -i .ssh/id_rsa"
    -og --chown=coreca:coreca
    "./immediate_certs/{{item}}_immediate_ca_cert_and_priv_key.pfx"
    "ansible@{{item}}:/home/coreca/keys/"
  with_inventory_hostnames:
    - certservers

- name: Remove immediate CA certificates and keys from config server
  file:
    path: ./immediate_certs
    state: absent
