---
- name: Install systemd unit file
  template:
    src: asl-certserver.service.j2
    dest: /etc/systemd/system/asl-certserver.service
    owner: coreca
    group: coreca
    mode: 0644

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable the service
  systemd:
    name: asl-certserver
    enabled: yes
    masked: no

- name: Start the service
  systemd:
    name: asl-certserver
    state: restarted
