---
- name: Creates directory
  file:
    path: /home/coreca/app
    state: directory
    owner: coreca
    group: coreca
    mode: 0770

- name: Download the latest release of CertServer
  get_url:
    url: https://github.com/Liblor/applied_security_lab_deploy/releases/latest/download/CertServer.tar.gz
    dest: /home/coreca/app/CertServer.tar.gz
    mode: 0640

- name: Unpack the downloaded archive
  unarchive:
    src: /home/coreca/app/CertServer.tar.gz
    dest: /home/coreca/app
    remote_src: yes

- name: Remove the archive
  file:
    state: absent
    path: /home/coreca/app/CertServer.tar.gz
