---
- name: Create folder for wordlist
  file:
    path: /usr/share/wordlists
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Move password list archive to {{ ansible_hostname }}"
  synchronize:
    src: /vagrant/password_list/rockyou.txt.bz2
    dest: /usr/share/wordlists/

- name: Extract password list
  command: bunzip2 /usr/share/wordlists/rockyou.txt.bz2

- name: Set permissions on password list
  file:
    path: /usr/share/wordlists/rockyou.txt
    owner: root
    group: root
    mode: 0644
